In [1]:
import numpy as np
import time, sys

In [8]:
x = np.arange(12).reshape((4, 3))
print(x)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [49]:
import numpy as np

x = np.array([1, 2, 3, 4, 5])

print(x)
print(x.ndim)

x = np.array([[[[1, 2, 3]]], [[[1, 2, 3]]], [[[1, 2, 3]]], [[[1, 2, 3]]], [[[1, 2, 3]]], [[[1, 2, 3]]]])
print(x)
print(x.ndim)


[1 2 3 4 5]
1
[[[[1 2 3]]]


 [[[1 2 3]]]


 [[[1 2 3]]]


 [[[1 2 3]]]


 [[[1 2 3]]]


 [[[1 2 3]]]]
4


In [42]:
e = np.arange(5)
print(e)

e = [0 1 2 3 4]


In [50]:
class stuff:
  # a simple class for simple comparisons
  def __init__(self, num1, num2):
    n = num1
    m = num2

# constructing two different objects with the same data
s = stuff(2, 4)
t = stuff(2, 4)

# seeing if these objects are equal
print(s == t)

# how about if we set a new variable to s?
x = s
print(s == x)

# this peculiarity is caused by the default equivalence method (which is secretly being called by using "==") checking to see if the object references in the variables is the same

# you can override this within the class definition by overwriting the __eq__ method
class stuff2:
  # same class as before, but with a tweak
  def __init__(self, num1, num2):
    n = num1
    m = num2
  # overwriting the equivalence method to compare this object's stored values to the other's
  def __eq__(self, other):
    if other:
      return self.n == other.n and self.m == other.m

# constructing two different objects with the same data
s = stuff2(2, 4)
t = stuff2(2, 4)

# now are these objects considered equal?
print(s == t)

False
True


AttributeError: 'stuff2' object has no attribute 'n'